dotnet/install-scripts

- CODE-OF-CONDUCT.md
Added code of conduct as requested here: https://github.com/dotnet/org-policy-violations/issues/1146
> Added CODE-OF-CONDUCT

- src/dotnet-install.ps1
> Fix: installing for wrong architecture

- azure-pipelines.yml
- src/MonitoringFunctions/Functions/Ps1Downloader.cs
- src/MonitoringFunctions/Functions/ShDownloader.cs
- src/MonitoringFunctions/Functions/WorkItemCreator.cs
- src/MonitoringFunctions/Models/AlertEvaluation.cs
- src/MonitoringFunctions/Models/AlertNotificationData.cs
- src/MonitoringFunctions/Models/AlertState.cs
- src/MonitoringFunctions/MonitoringFunctions.csproj
- tests/MonitoringFunctions.Test/Assets/SampleAlertNotificationData.json
- tests/MonitoringFunctions.Test/MonitoringFunctions.Test.csproj
- tests/MonitoringFunctions.Test/TestAlertDataDeserialization.cs
Delivers work item [#1121215](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1121215)
- Created a new function that:
Waits for a web request from grafana
Parses the request body
Creates work item for each metric that has passed the threshold
- Added a unit test (open to ideas for more unit tests).
- Updated build pipeline SDK version to 3.1 which is needed for "Validate SDK" step
> Added function to create work items

- src/dotnet-install.ps1
- src/dotnet-install.sh
Delivers #38.  Change repo from sdk to install-scripts in scripts' exception messages.
> Change repo from sdk to install-scripts in scripts

- src/MonitoringFunctions.Windows/Functions/WorkItemCreator.cs
- src/MonitoringFunctions.Windows/Incidents/IncidentSerializer.cs
- src/MonitoringFunctions.Windows/Incidents/Models/CommonContent.cs
- src/MonitoringFunctions.Windows/Incidents/Models/Detection.cs
- src/MonitoringFunctions.Windows/Incidents/Models/Impact.cs
- src/MonitoringFunctions.Windows/Incidents/Models/ImpactedScript.cs
- src/MonitoringFunctions.Windows/Incidents/Models/Incident.cs
- src/MonitoringFunctions.Windows/Incidents/Models/RcCategory.cs
- src/MonitoringFunctions.Windows/Incidents/Models/RecoveryStep.cs
- src/MonitoringFunctions.Windows/Incidents/Models/RootCause.cs
- src/MonitoringFunctions.Windows/Incidents/Models/Symptom.cs
- src/MonitoringFunctions.Windows/Incidents/Serialization/Providers/Json/JsonSerializer.cs
- src/MonitoringFunctions.Windows/Incidents/Serialization/Serializer.cs
- tests/MonitoringFunctions.Test/Assets/SampleNewIncident.json
- tests/MonitoringFunctions.Test/Assets/SampleResolvedIncident.json
- tests/MonitoringFunctions.Test/MonitoringFunctions.Test.csproj
- tests/MonitoringFunctions.Test/TestIncidentSerializer.cs
- tests/MonitoringFunctions.Test/TestUtilities.cs
- Note none of the incident models are meant to be compared or sorted; thus, IComparable was not implemented 
- All unit tests passed
> 1st drop for incident content serialization in work items.

- src/dotnet-install.ps1
https://github.com/dotnet/sdk/pull/10940 PR didn't get to this repo, adding it.
Also should fix part of https://github.com/dotnet/install-scripts/issues/25#issuecomment-330969941
> repeating dotnet/sdk#10940: exit 0 to return replacement

- tests/Install-Scripts.Test/GivenThatIWantToInstallTheSdkFromAScript.cs
Reenabled previously disabled unit tests
Added more tests for aspnetcore
> reenabled disabled tests

- src/dotnet-install.ps1
- src/dotnet-install.sh
Delivers issue #27. Improve the "... failed to install with an unknown error" message.
> Improve an error message

- src/dotnet-install.sh
> Add retry to .sh script

- src/dotnet-install.sh
> Corrected time in sleep function

- tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs
- tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
Delivers #141 
Please check each commit individually or you will see a lot more changes. The changes are basically:
- One file was renamed
- Another new test file was added
> Add new tests

- src/dotnet-install.ps1
> Support hidden ~/.dotnet directories

- src/dotnet-install.ps1
Fixes https://github.com/dotnet/install-scripts/issues/155
> Continue on error during disk space checks

- azure-pipelines.yml
Changes are tightly coupled to corresponding resources in Azure.
> Move linux app functions to new resource group 'Dotnet-Install-Monitoring-Functions'

- src/dotnet-install.ps1
- src/dotnet-install.sh
Some aka.ms links are redirecting to other aka.ms links. This change makes sure we follow them until we reach the final URL.
> Follow multiple redirects

- src/dotnet-install.ps1
this parameter will control how much time allow for downloading SDK
Closes #195
> Add timeout parameter

- src/dotnet-install.ps1
> Disable retries on 404

- src/dotnet-install.ps1
- tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs
Fixes https://github.com/dotnet/install-scripts/issues/189
> Add alias to installdir

- src/dotnet-install.sh
> Fix: machine_has is not working reliably on Alpine

- azure-pipelines.yml
- tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
We don't test the scripts in MacOS today. This change will run tests on MacOS as well.
> Run tests on Macos

- src/dotnet-install.ps1
- src/dotnet-install.sh
- tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
- tests/Install-Scripts.Test/Utils/CommandResultAssertions.cs
Fixes https://github.com/dotnet/install-scripts/issues/229
> Search archives in multiple feeds

- src/MonitoringFunctions.Windows/MonitoringFunctions.Windows.csproj
remove deprecated dependency according to https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-install-scripts/alert/6567780?typeId=6427340
> remove outdated dependency

- src/dotnet-install.sh
- tests/Install-Scripts.Test/Assets/.gitattributes
- tests/Install-Scripts.Test/Assets/InstallationScriptTestsWithWindowsLineEndings.json
- tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs
- tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
- tests/Install-Scripts.Test/Install-Scripts.Test.csproj
fix parsing of line endings for bash script - [#308](https://github.com/dotnet/install-scripts/issues/308)
> fix parsing of line endings for bash script

- src/dotnet-install.ps1
We want to know, how much time it takes for some actions.
> Added time measurements for several actions

- src/Signing/SignScripts.csproj
Preparation for bash script signing.
> Added MicroBuild signing for bash script

- src/Signing/SignScripts.csproj
Reverting all changes as CI is still failing to sign PS1.
> Full revert

- azure-pipelines-official.yml
- Update the codeSignValidation parameters to exclude the Test Binaries produced from the validation. 
- Make the codeSignValidation parameter to 'break' mode.
> Update the code signValidation parameters

- src/dotnet-install.sh
cc @dotnet/samsung, @akoeplinger
```sh
$ docker run --rm --platform linux/riscv64 alpine uname -m
riscv64
```
> Detect riscv64 architecture

- azure-pipelines-official.yml
> Enable policheck and tsa

- src/dotnet-install.ps1
fixes #541 
remove nonascii characters
> remove emoji - fix signing issue on non-"en-US" locales
