dotnet/install-scripts

.gitattributes
Fixes #39 
Added a .gitattributes file so that any .ps1 or .sh file pushed or checked out will have LF line endings.
=> Add .gitattributes to enforce line endings for scripts

.gitattributes
Relates to #40 
.ps1 script signature cannot be validated if the signature block doesn't have CRLF line endings. This pr ensures that .ps1 always has CRLF line endings.
=> Add .gitattributes to enforce correct line endings for scripts

azure-pipelines.yml
Delivers #35 
Our build pipeline was signing the scripts, but were not checking to see if the signatures are really there and valid.
This PR makes sure signatures are validated before build succeeds.
Validation only occurs on internal builds, not PR val builds.
=> Added signature validation

src/dotnet-install.ps1
Delivers #56 
This change will only be effective in the case that the executing environment doesn't support `Write-Host` and `Write-Output`. So a regression is not expected.
=> Fallback to Write-Output when other options are unavailable

src/dotnet-install.ps1
Required for actions/setup-dotnet#71. Agents can set proxy settings for their runs which include addresses which should not go through the proxy. This script doesn't allow that value to be specified for windows. In the shell script this is handled by wget and curl both honoring the environment variables `https_proxy` and `no_proxy`.
=> Allow Bypass list to be passed into the proxy

src/dotnet-install.ps1
ProxyBypassList must not be null.
Otherwise setting it on the proxy object throws an exception.
=> ProxyBypassList must not be null

azure-pipelines.yml
Internal build fails to find a proper SDK version to install. Caused by https://github.com/dotnet/install-scripts/pull/62
Updated request number to fix.
=> Fix: Internal build fails

azure-pipelines.yml
Internal builds are failing because arcade validation step encounters an error about installed sdk version.
Initial discussion in "Arcade - First Responders" Teams channel signals that this step is not needed in this repo. Other arcade-based repos under dotnet are also not running this step.
Therefore, this PR removes that validation step from our build pipeline.
=> Removed arcade validation build step

src/dotnet-install.sh
The warning message in dotnet-install.sh when it fails to find libttng indicates that you need to install libcurl which could be slightly confusing.
=> Fix typo in prerequisite check in dotnet-install.sh

src/dotnet-install.ps1, src/dotnet-install.sh
This stems from the changes (which will be rolled back if and when this change becomes available in the "normal" scripts) done as part of https://github.com/dotnet/arcade/pull/6051.  
The changes in this PR are a copy of the scripts added in https://github.com/dotnet/arcade/tree/master/eng/common/dotnet-install-scripts .  I've simply made it such that the scripts will look for the existence of productVersion.txt, and if found use this instead of the "specificVersion" variable to resolve the path to the package(s) being downloaded and unzipped.
=> Changes to understand productVersion.txt if found in container with a build

src/dotnet-install.sh, tests/Install-Scripts.Test/Assets/InstallationScriptTestsWithMultipleSdkFields.json, tests/Install-Scripts.Test/Assets/InstallationScriptTestsWithVersionFieldInTheMiddle.json, tests/Install-Scripts.Test/GivenThatIWantToInstallTheSdkFromAScript.cs, tests/Install-Scripts.Test/Install-Scripts.Test.csproj
For #7 
Running install script `scripts/obtain/dotnet-install.sh` with `jsonfile` argument works on macOS only when `sdk` section has a single property `version`. When `sdk` section has multiple properties, for example,
```json
"sdk": {
"version":  "5.0.100-preview.6.20310.4",
"allowPrerelease": true,
"rollForward": "major"
}
```
a version is detected as `5.0.100-preview.6.20310.4allowPrerelease:truerollForward:major`.
Also, in a case when `version` is not the first property in `sdk` a version can not be detected returning an error ``dotnet_install: Error: Unable to find the SDK:version node in `global.json` ``.
The problem seems to be in line:
```
sdk_list="$(echo -e "${sdk_list}" | tr -d '[[:space:]]')"
```
On macOS, echo does not have a `-e` argument, and all lines of key-value pairs …
=> Fix SDK version parsing from global.json in install script on macOS

src/dotnet-install.ps1, src/dotnet-install.sh
Concerns issues #6, #36, #72.
The dependencies check is currently broken: 
- it is out of date, 
- it is not full (and can't be full): for different versions, for runtime/SDK, there might be different sets of dependencies, 
- the warnings are misleading, as they do not specify that it is a library name, not a package name, which has not been found.
To support these checks properly (more/less full and not out of date) we would need too big of an effort. It is doubtful that some checks always are better than none: we are worried that the customer would see the warning, add the library, and would not understand why dotnet still does not work, as a result of incompleteness of a check.
Based on these, we decided to remove them and instead always ask the customer to visit the documentation page …
=> Removing dependencies check, adding a link to documentation page

src/dotnet-install.ps1, src/dotnet-install.sh
Delivers issue #43. Adding a warning so that people who want to install a runtime to run apps should use other installation options.
=> Add info messages concerning install scripts purpose

src/dotnet-install.ps1, src/dotnet-install.sh
Addressing @mairaw s comments here: https://github.com/dotnet/website/pull/2418
The word "please" was removed and the URLs that point to .Net Core dependency doc page no longer contain locale.
=> Updated help strings and urls

src/dotnet-install.sh
Delivers https://github.com/dotnet/install-scripts/issues/98
Changes:
- During the download of `product.version` file, the script now checks if `curl` or `wget` is available on the system before attempting a download.
=> Check if curl or wget is installed

src/dotnet-install.ps1, src/dotnet-install.sh
fixes dotnet/install-scripts#64: removes coherent special option for --version parameter. 
Coherent option is not supported any longer
=> removed coherent version option

src/dotnet-install.ps1, src/dotnet-install.sh
fixes dotnet/install-scripts#45:
- install-scripts.sh - temp zip file is now removed before script exits
- install-scripts.ps1 - added removing of zip file in case of download failure and log messages
=> install scripts should remove temp zip file

src/dotnet-install.ps1
Partially delivers issue #27 and issue #9. 
This is the first part of planned fixes of error diagnosis in the scripts. The changes partially fix exceptions' swallowing.
Also, this closes the debts from PR #96 and PR #97.
=> Fix exceptions' swallowing

src/MonitoringFunctions.Common/DataService/IDataService.cs, src/MonitoringFunctions.Common/DataService/Providers/DummyDataService.cs, src/MonitoringFunctions.Common/DataService/Providers/KustoDataService.cs, src/MonitoringFunctions.Common/HelperMethods.cs, src/MonitoringFunctions.Common/Models/HttpRequestLogEntry.cs
Addresses #107 
Notes:
1. Updated IDataService with an ReportUrlAccessAsync overload, accepting an HttpRequestLogEntry instance
1. Updated the IDataService providers accordingly
1. HelperMethods.CheckAndReportUrlAccessAsync to use the new ReportUrlAccessAsync overload
The previous implementation, was instead relying on HttpResponseMessage instances which neither HelperMethods.CheckAndReportUrlAccessAsync nor the Kusto IDataService provider were disposing.
=> #107 addressed monitoring failures due to uncaught exceptions

src/dotnet-install.ps1, src/dotnet-install.sh
Second PR concerning exceptions' handling. Addresses issues #27, #11, #9, #8.
Changes:
- Add functions for getting HTTP headers.
- Make download errors visible (including the TLS issue).
- Error 404 is now processed separately: for some of the cases, getting error 404 is a normal flow of script execution. 
- Fix extraction failure processing.
=> Fix exceptions' handling

src/dotnet-install.sh
dotnet/install-scripts#13:
Part 1: use of --runtime-id generates incorrect primary URL for linux-musl-x64
=> fixes dotnet/install-scripts#13: use of --runtime-id generates incorrect primary URL for linux-musl-x64

src/dotnet-install.sh
The changes fix the two situations when architecture detection is currently wrong:
- The kernel is 64-bit, the kernel truthfully reports that it is 64-bit, but the OS is 32-bit (removed, decided not to fix)
- The kernel is 64-bit, the kernel lies and reports that it is 32-bit, but the OS is 32-bit
=> Fix default architecture detection

src/dotnet-install.sh
Implements suggestion in: https://github.com/dotnet/install-scripts/issues/13#issuecomment-593521037
--os option allows user to specify the OS to be used when selecting the installation package.
Important notes to review:
- the implementation is done only for primary links. For legacy links, there is a wider range of supported OS, and I don't want to mix both sets together. I suggest those who want to override OS for legacy links may still use --runtime-id.
- the allowed values for --os are: `linux, linux-musl, osx, freebsd, rhel.6` - aligned with possible choices for OS auto-detection. I'm not sure about including `freebsd` and `rhel.6` - I haven't seen and freebsd specific packages, and packages for `rhel.6` are rare. According to https://github.com/dotnet/installer rhel.6 packages are …
=> added --os option to bash script

src/dotnet-install.sh
On macos-arm64 `uname -m` returns `arm64`.  Update `get_machine_architecture()`
=> Support macos-arm64

src/dotnet-install.ps1, tests/Install-Scripts.Test/GivenThatIWantToInstallTheSdkFromAScript.cs
fixes https://github.com/dotnet/install-scripts/issues/116 and https://github.com/dotnet/install-scripts/issues/105#issuecomment-730428570 
Starting 5.0, use `<feed location>/WindowsDesktop` for `windowsdesktop` runtime.
=> Powershell: changed the location of windows desktop runtime starting 5.0

src/dotnet-install.sh
Should fix https://github.com/dotnet/install-scripts/issues/136
=> Consult http_code and download_error_msg only for failed downloads.

src/dotnet-install.sh
This was reported in https://github.com/dotnet/install-scripts/issues/125 and I just had another report of this in a different context.
There's no reason why we should fail to install dotnet just because we couldn't get the colors, so harden against `tput` failing.
=> Harden tput command against unset TERM

src/dotnet-install.ps1, src/dotnet-install.sh, tests/Install-Scripts.Test/AkaMsLinksTests.cs, tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs, tests/Install-Scripts.Test/TestBase.cs, tests/Install-Scripts.Test/Utils/Quality.cs
fixes https://github.com/dotnet/install-scripts/issues/12
Added the resolution of download link via aka.ms links as primary method; the current implementation is kept as the fallback
Added the support for specifying the quality for build in certain channel (supported with aka.ms links only for 5.0+ versions)
Added unit and integration tests.
=> [draft] aka.ms links support

src/dotnet-install.ps1, src/dotnet-install.sh, tests/Install-Scripts.Test/AkaMsLinksTests.cs, tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs, tests/Install-Scripts.Test/Utils/CommandResultAssertions.cs
Changes in this PR:
- Adding --internal switch for aka.ms links.
- Fixing usage of the credentials for aka.ms links (previously credentials were applied twice and as a result the final link had wrong format).
- Prevent echoing of credentials given --feed-credential switch.
Delivers issue #169.
=> Add internal switch

src/dotnet-install.sh
Fixes https://github.com/dotnet/install-scripts/issues/216
**Problem:** Some options of `wget` are not available on Alpine.
**Solution:** The changes in this PR detects the missing options and removes them.
The implication of this removal will be that scripts running on alpine+wget will be quicker to give up on retrying. This should be acceptable considering that:
- We already have a custom retry logic built-in in a higher level,
- The issue can simply be resolved by installing curl.
=> Don't use unavailable wget options

azure-pipelines.yml, eng/validate-sdk.yml, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
Noted while cleaning up arcade stuff, this repo seems to be using the .Arcade queues which will be deleted soon as they were only for Arcade and we're not supposed to be using them any more (Arcade isn't)
=> Move off Arcade-Pool-Provider

src/MonitoringFunctions.Common/MonitoringFunctions.Common.csproj, src/MonitoringFunctions.Linux/MonitoringFunctions.Linux.csproj, src/MonitoringFunctions.Windows/MonitoringFunctions.Windows.csproj
Patch for the vulnerability https://github.com/dotnet/runtime/issues/49377
This PR updates vulnerable versions of `System.Text.Encodings.Web` (4.5.0) and `Microsoft.AspNetCore.Http` (2.1.0) to versions 4.5.1 and 2.1.22 respectively.
Both of these dependencies are referenced by `Microsoft.NET.Sdk.Functions`, which is likely to be updated to contain the secure versions of these packages. However, as of today, even the latest version of `Microsoft.NET.Sdk.Functions` package still references the vulnerable versions. Therefore, fix in this PR includes explicitly referencing the packages in the affected projects.
=> Update System.Text.Encodings.Web version 4.5.1

src/dotnet-install.ps1, src/dotnet-install.sh, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
Fixes #241
Attempting to install an already installed version now exits with success instead of failure.
=> Bash script returns failure if the sdk is already installed

src/dotnet-install.sh, tests/.gitignore, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=6.0.100_runtime=.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs, tests/Install-Scripts.Test/Install-Scripts.Test.csproj, tests/Install-Scripts.Test/TestBase.cs
This PR updates the bash script to use the correct legacy links.
=> Wrong legacy links are created on bash script

src/dotnet-install.sh
fix bashscript for run in `sudo sh` environment.
Guideline for fix: [SC2181](https://github.com/koalaman/shellcheck/wiki/SC2181)
Install-scripts log with applied changes
```
ykovalova@NETUXs-MacBook-Pro ~ % sudo sh dotnet-install.sh --version "6.0.200" --install-dir "/Users/runner/hostedtoolcache888/dotnet" --verbose
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer. …
```
=> fix bashscript for run in sudo sh environment

src/dotnet-install.sh
Fix #259 
1. Test `wget -h` output for the two extra parameters we want to use, and only attempt to use them if we see them there. Pipe to /dev/null so that there's no visible output.
2. Leave the fallback path in to reduce risk. However BusyBox wget sets exit code 1 when there are unexpected parameters and GNU wget returns 2. Fix this path by checking for either.
Tested on Alpine and Ubuntu (forcing the wget path). Verified it works, and that on Ubuntu it does use the extra wget parameters.
=> Fix wget path on Alpine

src/dotnet-install.sh
Fix #285
This PR https://github.com/dotnet/install-scripts/pull/278 introduced a check and based on the error message it seems to be validating that at least --version or --quality is specified.  The current `if` statement doesn't do this correctly, it's comparing only if `--version latest` isn't specified and `-n` does the opposite of checking if `--quality` is empty.
Used https://linuxhint.com/testing_strings_bash_z_n as a resource on the difference of now `-n` and `-z` works for bash `if` statement for strings.  Where `-n` returns true if the string is NOT null, and `-z` returns true if the string IS null.
Note that are other usage of `-n` in the script and I didn't validate if those are correct.  I only tested this change locally that the way our CI uses dotnet-install.sh with both …
=> Fix check if version and quality are not specified

src/dotnet-install.ps1, src/dotnet-install.sh, tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs, tests/Install-Scripts.Test/Utils/Quality.cs
revert 286 according to https://github.com/dotnet/install-scripts/issues/287, improve error message for case when quality and version are both specified, extend test coverage
Documentation is also updated 
[https://github.com/dotnet/docs/pull/30005](https://github.com/dotnet/docs/pull/30005)
=> revert 286 + extend test coverage

src/dotnet-install.sh
s390x support was introduced in .NET 6, and even though the
corresponding binaries are not distributed via
dotnetcli.azureedge.net, it is possible to get them from a custom feed.
When preparing a tarball for the source build, one could use this as
follows:
```
./build.sh -runtimesourcefeed /path/to/feed /p:DotNetRuntimeSourceFeed=/path/to/feed ...
```
=> Support s390x

src/dotnet-install.ps1, src/dotnet-install.sh, testEnvironments.json, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs, tests/Install-Scripts.Test/Install-Scripts.Test.csproj
Add the script's purpose to the help text
Resolves #351
=> Reduce verbosity of the script by default

src/dotnet-install.sh
.NET 7 supports ppc64le architecture. Microsoft does not generate and uploads binaries at dotnetcli.azureedge.net as it is community supported architecture. But it is possible to get them from a custom feed.
When preparing a tarball for the source build, one could use this as follows:
`./build.sh -runtimesourcefeed /path/to/feed /p:DotNetRuntimeSourceFeed=/path/to/feed ...`
Note: eng/common folder is yet not in sync with latest arcade. Issue https://github.com/dotnet/install-scripts/issues/345 has been opened for the same.
=> add support for ppc64le in install-script

src/dotnet-install.ps1
#374
For older PS versions it is a known issue: 
[build.cmd error dotnet-install: There is not enough disk space on drive C · Issue #35301 · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/issues/35301)
[Get-PSDrive C returns blank used/free disk space · Issue #12442 · PowerShell/PowerShell (github.com)](https://github.com/PowerShell/PowerShell/issues/12442)
This fix loosens the check for PS with versions < 7.
=> change diskspace check due to PS issues

src/dotnet-install.ps1
Fixes: https://github.com/dotnet/install-scripts/issues/374
Solution: the previous warning is chatty because most of the build machines have PS version < 7. 
Make it available in verbose mode.
=> update severity level on disk space check operation

src/dotnet-install.sh
**Description**
The loongarch64 binaries are not distributed via dotnetcli.azureedge.net yet, it is possible to get them from a custom feed.
=> Add support for loongarch64 architecture

src/dotnet-install.sh
https://github.com/dotnet/install-scripts/issues/396
GNU stat can be specified in PATH before BSD one.
stat from /usr/bin/stat is needed for our purposes.
=> use stat from /usr/bin/stat explicitly

tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenMacosIsPassedToBash.verified.txt, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
After recent LTS version upgrade current tests are failing. 
The PR is updating current state of some tests which involves downloading LTS version of sdk or specific runtimes. 
It is also a prerequisite for the https://github.com/dotnet/install-scripts/pull/411 to complete.
=> Tests updates after release dotnet 8

eng/common-variables.yml, eng/validate-sdk.yml
There is a variable group DotNet-Blob-Feed is referenced from the pipelines, and will be removed soon as part of this issue: https://github.com/dotnet/arcade/issues/13963. 
After upgrading to the dotnet 8 arcade there is no references left to this variable group its variables. 
Removing the variable group DotNet-Blob-Feed  from the pipeline
=> Remove unused variable group from pipelines

tests/Install-Scripts.Test/Install-Scripts.Test.csproj
Currently referenced packages from Microsoft.DotNet.Cli.Utils are loaded implicitly during build process, hence the referenced packages versions differ from the required by the dependency and choosing the closest one. 
Example of process before: https://dev.azure.com/dnceng-public/public/_build/results?buildId=476794&view=logs&j=d6d0747d-862c-5953-c201-f4e1a93f2cef&t=f8f9cedb-7045-5b9b-3dc7-4063f90e4dfe 
Example of process for this PR: https://dev.azure.com/dnceng-public/public/_build/results?buildId=476832&view=logs&j=d6d0747d-862c-5953-c201-f4e1a93f2cef&t=f8f9cedb-7045-5b9b-3dc7-4063f90e4dfe
Specify the exact version of the packages explicitly in the project file.
=> Upgrade Microsoft.DotNet.Cli.Utils referenced packages

src/dotnet-install.sh
Raspberry Pi 4/5 supports running 32-bit user land with a 64-bit Linux kernel. Detect that and install linux-arm version of .NET instead of linux-arm64. The arm64 version doesn't work in that scenario.
=> Detect ARMhf userland on top of AARCH64 kernel

src/install-dotnet-preview.sh
The current script is linked in https://github.com/dotnet/core/blob/main/release-notes/9.0/install-linux.md but does not support the installation of 9.0.0-preview. This update the links to install the current .net 9 preview.
=> Update install-dotnet-preview.sh to support install of 9.0.0-preview

src/dotnet-install.sh
otherwise messages like
> dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-preview.1.24101.2/dotnet-sdk-9.0.100-preview.1.24101.2-linux-x64.tar.gz
don't make much sense.
=> use neutral terminology

src/dotnet-install.sh
#444
Split armv6 or below from the case `arm` in getting machine architecture. Then fail if the architecture is armv6 or below.
=> Fail on unsupported ARM architecture levels

src/dotnet-install.sh, tests/Install-Scripts.Test/AkaMsLinksTests.cs, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs
#461
In the case that the response ends without final code 2xx/4xx/5xx, getting broken redirects includes last http code.
=> Correct broken redirects in the case that the response ends without final code 2xx/4xx/5xx

docs/README.md
The build status links and actual status is not up to date. 
Updated the link to properly point to the public builds
Example: https://github.com/f-alizada/install-scripts/tree/dev/f-alizada/update-build-status?tab=readme-ov-file
=> Update the build status id in the links

src/dotnet-install.sh
IBM Power architecture is not correctly detected on FreeBSD 15.0-CURRENT
this patch is one step towards the bringup on this arch
but the script fails because Microsoft don't provide any pre-built PPC dotnet sdk (another issue)
=> detect IBM Power architecture

src/dotnet-install.ps1
#494
https://learn.microsoft.com/en-us/dotnet/core/install/windows has been re-wrote and **Dependeices** section was changed to be [Supported versions](https://learn.microsoft.com/en-us/dotnet/core/install/windows#supported-versions). Modify the note in the script to reflect this.
=> Change the note on Windows dependencies to supported Windows versions

src/dotnet-install.ps1
#496
Add the check that tests if user has write access to install root. If user doesn't have, fail the installation with an error telling running as administrator.
Additionally, if user specifies the install root via environment variable `DOTNET_INSTALL_DIR` to the sub folder of `$env:ProgramFiles\dotnet`, warn that it's better to keep aligned with .NET SDK installer.
=> Check if user has write access to the install root

src/dotnet-install.sh
It was downloading osx-x64 on osx-arm64 machine due to relaxed pattern matching:
```sh
$ ./dotnet-install.sh --quality daily --channel "10.0" --install-dir ~/.dotnet10 -verbose
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: …
```
=> Fix net10.0 detection for osx-arm64

src/dotnet-install.sh
Fixes #520
The script name in the `help` is now hard-coded.
=> Name of the string in the help string is now hardcoded (.sh version)

src/dotnet-install.ps1, src/dotnet-install.sh, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=8.0.303_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=9.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=8.0.303_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=9.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenMacosIsPassedToBash.verified.txt
In preparation for new CDNs for .NET Builds, we are making the scripts resilient to CDN changes.
In the current default mode of execution, the scripts use the channel, quality, and other inputs to look up an aka.ms link that redirects to the current best-known version of the product that the user requested. For example, `./dotnet-install.sh --channel 9.0 --quality ga` might use the url `https://aka.ms/dotnet/9.0/dotnet-sdk-linux-x64.tar.gz` when on an x64 Linux host to download the appropriate version of the SDK.
This url used to be accepted wholesale, but with the new CDN and incremental cleanup of various aka.ms links, we cannot rely on 100% data correctness. In order to buffer these changes, instead of directly using the aka.ms redirect, we'll instead use it to probe the set of known …
=> Implement fallback detection of redirects for the new CDNs

src/dotnet-install.sh
Fix spelling in string "Cound not construct a legacy_download_link; omitting..."
=> Fix spelling in error string

src/dotnet-install.sh
https://github.com/dotnet/vscode-dotnet-runtime/issues/2074#issuecomment-2573781465
Fixes http error being swallowed. We print it in powershell, this harmonizes the behavior.
=> print http code on download failure

src/dotnet-install.ps1, src/dotnet-install.sh, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=8.0.303_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToBash_version=9.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=1.0.5_runtime=dotnet.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=2.1.0_runtime=aspnetcore.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=6.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=8.0.303_runtime=null.verified.txt, tests/Install-Scripts.Test/Assets/GivenThatIWantToGetTheSdkLinksFromAScript.WhenAnExactVersionIsPassedToPowershell_version=9.0.100_runtime=null.verified.txt, tests/Install-Scripts.Test/GivenThatIWantToGetTheSdkLinksFromAScript.cs
=> remove no-cdn concept, remove azureedge links

src/dotnet-install.ps1, src/dotnet-install.sh
fixes #570 
the links were updated so the backup parsing is no longer needed
=> remove backup parsing

src/dotnet-install.ps1, src/dotnet-install.sh, tests/Install-Scripts.Test/AkaMsLinksTests.cs, tests/Install-Scripts.Test/GivenThatIWantToInstallDotnetFromAScript.cs, tests/Install-Scripts.Test/Utils/Quality.cs
After looking at usage data for the aka.ms links that back these qualities, it's clear that the only usage is from the tests in the install scripts repo itself. Removing these links has significant benefit to the overall time it takes to run our staging pipelines, as well as overall maintainability.
=> Remove support for Signed and Validated qualities

src/dotnet-install.sh
Fixes https://github.com/dotnet/install-scripts/issues/610
Related to https://github.com/curl/curl/issues/17554.
Curl 8.14.0 was returning a zero-exit code even when the output indicated a failure, such as curl: (22) The requested URL returned error: 404. This behavior resulted in failures as described in https://github.com/dotnet/install-scripts/issues/610.
=> Handle curl 8.14.0 zero-exit bug
